//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace practicaAngularjs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vehiculos
    {
        public long idvehiculos { get; set; }
        public string tipovehiculo { get; set; }
        public string modelo { get; set; }
        public string marca { get; set; }
        public Nullable<long> cantidad { get; set; }
        public Nullable<long> idusuario { get; set; }
    
        public virtual Usuarios Usuarios { get; set; }
    }
}
